# Generated by Django 4.1.2 on 2023-04-02 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='undefined', max_length=400)),
                ('phone2', models.CharField(max_length=400, null=True)),
                ('iban', models.CharField(default='undefined', max_length=34)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='undefined', max_length=200)),
                ('type', models.CharField(choices=[('re', 'Residence'), ('fl', 'Flat'), ('ro', 'Room')], default='ro', max_length=2)),
                ('size', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=400)),
                ('price', models.IntegerField(default=0)),
                ('landlord', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='tpl.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='undefined', max_length=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('property', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='tpl.property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpl.tenant')),
            ],
        ),
    ]
