# Generated by Django 4.1.2 on 2023-05-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpl', '0004_alter_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('room', 'Room'), ('residence', 'Residence'), ('flat', 'Flat')], default='room', max_length=9),
        ),
    ]
