# Generated by Django 4.1.2 on 2023-05-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpl', '0006_property_city_alter_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('prague-albania', 'Prague'), ('brno-czech_republic', 'Brno'), ('undefined', 'Undefined'), ('tirana-czech_republic', 'Tirana')], default='undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('room', 'Room'), ('flat', 'Flat'), ('residence', 'Residence')], default='room', max_length=9),
        ),
    ]
