# Generated by Django 4.1.2 on 2023-05-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpl', '0007_alter_property_city_alter_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('brno-czech_republic', 'Brno'), ('undefined', 'Undefined'), ('tirana-albania', 'Tirana'), ('prague-czech_republic', 'Prague')], default='undefined', max_length=50),
        ),
    ]
